name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t nginx-test .
    - name: "test run"
      run: docker run -d -p 888:88 nginx-test
    - name: "test curl "
      run: curl  localhost:888/index.html

